// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'


// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token = null;
    if (typeof window !== "undefined") {
      token = localStorage.getItem("jwt_token");
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
