// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import jwt from 'jsonwebtoken';



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    try {
      const JWT_SECRET = process.env.JWT_SECRET || "fallback_secret_for_dev_only_change_in_prod";
      
      const request = getRequest();

      if (!request?.headers) {
        throw new Error('Unauthorized: No request headers available');
      }

      const authHeader = request.headers.get('authorization');

      if (!authHeader) {
        throw new Error('Unauthorized: No authorization header provided');
      }

      if (!authHeader.startsWith('Bearer ')) {
        throw new Error('Unauthorized: Only Bearer tokens are supported');
      }

      const token = authHeader.replace('Bearer ', '');
      if (!token) {
        throw new Error('Unauthorized: No token provided');
      }

      const decoded = jwt.verify(token, JWT_SECRET) as { sub: string; email: string };
      
      return next({
        context: {
          supabase: null, // Stubbed out
          userId: decoded.sub,
          claims: { sub: decoded.sub, email: decoded.email },
        },
      });
    } catch (err: any) {
      require("fs").writeFileSync("middleware-error.log", err.stack || err.message);
      throw err;
    }
  },
);
